version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-node-browsers
    steps:
      - checkout

      - restore_cache:
          name: Restore Clojure Deps Cache
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Yarn Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build the ClojureScript app with advanced optimizations
          command: yarn shadow-cljs release app

      - run:
          name: Run Clojure(Script) tests
          command: ./bin/test-all.sh

      - run:
          name: Compile SCSS into CSS
          command: ./bin/compile-scss.sh

      - save_cache:
          name: Save Clojure Deps Cache
          key: v1-dependencies-{{ checksum "deps.edn" }}
          paths:
            - ~/.m2
            - ~/.gitlibs
            - .cpcache
